#!/bin/bash
rm *.yaml && echo 'remove all yaml' 
sudo chmod -R 757 /opt
[ ! -d /opt/KUTR00101 ] && mkdir -p /opt/KUTR00101

# F1 Pod Logs (5%)
sudo rm -rf /opt/KUTR00101/*

# F2 Check Ready Node (4%)

# F3 NodeSelector (4%)

# F4 CPU (5%)

# F5 Multi-container (4%)

# F6 Sidecar (7%)

# F7

# F8

# F9

# F10

# F11

# F12

# F13

# F14

# F15

# F16

# F17
